### ISSUE TITLE
<Svrollbar /> adds multiple <style> tags inside <head> every time you scroll

### ISSUE THREAD

**Issue by oneezy** [daylilyfield/svrollbar#6]
When using `<Svrollbar>` to replace the **Window** scrollbar, each scroll adds 2 `<style>` tags to the `<head>`. The first is added when you start the scroll and another is added when it ends.

You can verify this by going to the [Svrollbar Website](https://daylilyfield.github.io/svrollbar/) , opening up dev tools and scrolling the page.

![image](https://user-images.githubusercontent.com/7369575/160273121-373e3b74-d0f4-4ba9-8395-db87aac0aec9.png)

**Comment by daylilyfield** [comment]
@oneezy thanks for your issue.  i can reproduce this issue on the svrollbar website served by github pages, but i can not reproduce it on my local pc.  hmm.   i try to figure out this issue, i will share you if i find out about it.

**Comment by daylilyfield** [comment]
@oneezy i found some issues and  PR in svelte github repository.
 
Issues
- sveltejs/svelte/issues/4801
- sveltejs/svelte/issues/7164

PR (not merged yet)
- sveltejs/svelte/pull/7260

a workaround i found for this issue is that [we should use svelte transition that are not turned into CSS transitions](https://github.com/sveltejs/svelte/issues/4801#issuecomment-625934949).

**Comment by oneezy** [comment]
ahh! so it's not `Svrollbar` specific issue and is `Svelte` specific issue.

**Comment by daylilyfield** [comment]
@oneezy yes, this issue will fix when svelte fixes it.  thank you for reporting.  let me close this issue.
